spring.application.name=sensitive-words-application
spring.datasource.url=jdbc:postgresql://localhost:5432/sensitivewords_db
spring.datasource.username=postgres
spring.datasource.password=Mike@1998

spring.jpa.hibernate.ddl-auto=create-drop
logging.level.root=DEBUG
server.servlet.context-path=/
